-- auto gen by  20170401 
truncate table game_room; -- 清空数据表
-- 初始化数据
insert into game_room("id", "game_id", "game_model_id", "name", "status", "description", "max_limit_player_number", "min_limit_player_blance", "per_desk_seat_count", "is_build_in", "jackpot", "jackpot_overflow") values (1,1,1,'香港',10,'低级场',200,1000,0,'t',1000000,0);
insert into game_room("id", "game_id", "game_model_id", "name", "status", "description", "max_limit_player_number", "min_limit_player_blance", "per_desk_seat_count", "is_build_in", "jackpot", "jackpot_overflow") values (2,1,1,'澳门',10,'低级场',200,1000,0,'t',1000000,0);
insert into game_room("id", "game_id", "game_model_id", "name", "status", "description", "max_limit_player_number", "min_limit_player_blance", "per_desk_seat_count", "is_build_in", "jackpot", "jackpot_overflow") values (3,1,1,'台北',10,'低级场',200,1000,0,'t',1000000,0);
insert into game_room("id", "game_id", "game_model_id", "name", "status", "description", "max_limit_player_number", "min_limit_player_blance", "per_desk_seat_count", "is_build_in", "jackpot", "jackpot_overflow") values (4,1,1,'北京',10,'低级场',200,1000,0,'t',1000000,0);
insert into game_room("id", "game_id", "game_model_id", "name", "status", "description", "max_limit_player_number", "min_limit_player_blance", "per_desk_seat_count", "is_build_in", "jackpot", "jackpot_overflow") values (5,1,1,'上海',10,'低级场',200,1000,0,'t',1000000,0);
insert into game_room("id", "game_id", "game_model_id", "name", "status", "description", "max_limit_player_number", "min_limit_player_blance", "per_desk_seat_count", "is_build_in", "jackpot", "jackpot_overflow") values (6,1,1,'广东',10,'低级场',200,1000,0,'t',1000000,0);
insert into game_room("id", "game_id", "game_model_id", "name", "status", "description", "max_limit_player_number", "min_limit_player_blance", "per_desk_seat_count", "is_build_in", "jackpot", "jackpot_overflow") values (7,1,3,'香港',10,'低级场',200,1000,0,'t',3000000,0);
insert into game_room("id", "game_id", "game_model_id", "name", "status", "description", "max_limit_player_number", "min_limit_player_blance", "per_desk_seat_count", "is_build_in", "jackpot", "jackpot_overflow") values (8,1,3,'澳门',10,'低级场',200,1000,0,'t',3000000,0);
insert into game_room("id", "game_id", "game_model_id", "name", "status", "description", "max_limit_player_number", "min_limit_player_blance", "per_desk_seat_count", "is_build_in", "jackpot", "jackpot_overflow") values (9,1,3,'台北',10,'低级场',200,1000,0,'t',3000000,0);
insert into game_room("id", "game_id", "game_model_id", "name", "status", "description", "max_limit_player_number", "min_limit_player_blance", "per_desk_seat_count", "is_build_in", "jackpot", "jackpot_overflow") values (10,1,3,'北京',10,'低级场',200,1000,0,'t',3000000,0);
insert into game_room("id", "game_id", "game_model_id", "name", "status", "description", "max_limit_player_number", "min_limit_player_blance", "per_desk_seat_count", "is_build_in", "jackpot", "jackpot_overflow") values (11,1,3,'上海',10,'低级场',200,1000,0,'t',3000000,0);
insert into game_room("id", "game_id", "game_model_id", "name", "status", "description", "max_limit_player_number", "min_limit_player_blance", "per_desk_seat_count", "is_build_in", "jackpot", "jackpot_overflow") values (12,1,3,'广东',10,'低级场',200,1000,0,'t',3000000,0);